global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orchard-service'
    static_configs:
      - targets: ['orchard-service:8080']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
